ALTER SESSION SET CONTAINER = DIGIOCEAN;
CREATE USER BODC IDENTIFIED BY bodc QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC;
CREATE USER BODC1 IDENTIFIED BY bodc1 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC1;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC1;

CREATE USER BODC2 IDENTIFIED BY bodc2 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC2;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC2;

CREATE USER BODC3 IDENTIFIED BY bodc3 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC3;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC3;

CREATE USER BODC4 IDENTIFIED BY bodc4 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC4;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC4;

CREATE USER BODC5 IDENTIFIED BY bodc5 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC5;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC5;

CREATE USER BODC6 IDENTIFIED BY bodc6 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC6;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC6;

CREATE USER BODC7 IDENTIFIED BY bodc7 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC7;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC7;

CREATE USER BODC8 IDENTIFIED BY bodc8 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC8;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC8;

CREATE USER BODC9 IDENTIFIED BY bodc9 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC9;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC9;

CREATE USER BODC10 IDENTIFIED BY bodc10 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC10;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC10;

CREATE USER BODC11 IDENTIFIED BY bodc11 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC11;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC11;

CREATE USER BODC12 IDENTIFIED BY bodc12 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC12;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC12;

CREATE USER BODC13 IDENTIFIED BY bodc13 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC13;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC13;

CREATE USER BODC14 IDENTIFIED BY bodc14 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC14;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC14;

CREATE USER BODC15 IDENTIFIED BY bodc15 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC15;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC15;

CREATE USER BODC16 IDENTIFIED BY bodc16 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC16;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC16;

CREATE USER BODC17 IDENTIFIED BY bodc17 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC17;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC17;

CREATE USER BODC18 IDENTIFIED BY bodc18 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC18;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC18;

CREATE USER BODC19 IDENTIFIED BY bodc19 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC19;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC19;

CREATE USER BODC20 IDENTIFIED BY bodc20 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO BODC20;
GRANT CREATE TABLE, DROP ANY TABLE, CREATE VIEW TO BODC20;
